# Generated by Django 4.2.3 on 2023-07-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=255)),
                ('address', models.GenericIPAddressField()),
                ('hostname', models.CharField(default='unknown', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BoardingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netbox_device_id', models.IntegerField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('MATCH', 'Match'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='NEW', max_length=255)),
                ('comment', models.TextField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webhook_listener.device')),
            ],
        ),
    ]
