# Generated by Django 4.2.3 on 2023-07-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_listener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardingprocess',
            name='netbox_device_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
