# Generated by Django 4.2.3 on 2023-07-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_listener', '0004_alter_boardingprocess_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardingprocess',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
