# Generated by Django 4.2.3 on 2023-07-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_listener', '0005_alter_boardingprocess_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardingprocess',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
