# Generated by Django 4.2.3 on 2023-08-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_listener', '0006_alter_boardingprocess_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardingprocess',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_process', to='webhook_listener.device'),
        ),
    ]
