# Generated by Django 4.2.3 on 2023-08-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_listener', '0007_alter_boardingprocess_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
